# hyperparams from trial 42
turbolander-2d-custom-v1:
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  n_steps: 500
  batch_size: 64
  gae_lambda: 0.9
  gamma: 0.999
  n_epochs: 10
  ent_coef: 4.481218636014261e-7
  max_grad_norm: 0.5
  learning_rate: 0.002036294186783434
  clip_range: 0.4
  vf_coef: 0.6120137329550599

# turbolander-2d-custom-v1:
#   n_envs: 16
#   n_timesteps: !!float 1e6
#   policy: 'MlpPolicy'
#   n_steps: 500
#   batch_size: 64
#   gae_lambda: 0.98
#   gamma: 0.999
#   n_epochs: 4
#   ent_coef: 0.01
