#turbolander-2d-custom-v1:
  #n_envs: 8
  #n_timesteps: !!float 1e6
  #policy: 'MlpPolicy'
  #batch_size: 256
  #learning_rate: !!float 3e-4
  #buffer_size: 1000000
  #ent_coef: 'auto'
  #gamma: 0.99
  #tau: 0.01
  #train_freq: 1
  #gradient_steps: -1
  #learning_starts: 10000
  #policy_kwargs: "dict(net_arch=[400, 300])"
  
turbolander-2d-custom-v1:
  n_envs: 8
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  batch_size: 256
  learning_rate: !!float 3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: -1
  learning_starts: 10000
  
#turbolander-2d-custom-v1:
  #n_envs: 8
  #n_timesteps: !!float 1e6
  #policy: 'MlpPolicy'
  #batch_size: 256
  #learning_rate: lin_7.3e-4
  #buffer_size: 1000000
  #ent_coef: 'auto'
  #gamma: 0.99
  #tau: 0.01
  #train_freq: 1
  #gradient_steps: 1
  #learning_starts: 10000
