!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 1000000
  - - ent_coef
    - auto
  - - gamma
    - 0.99
  - - gradient_steps
    - 1
  - - learning_rate
    - 0.0003
  - - learning_starts
    - 10000
  - - n_envs
    - 8
  - - n_timesteps
    - 1000000.0
  - - policy
    - MlpPolicy
  - - tau
    - 0.01
  - - train_freq
    - 1
